trainig_pipline_config:
  pipeline_name: Movies
  artifact_dir: artifact  #output directory

data_ingestion_config:
  dataset_download_url: "https://hello.com/data/new/train.csv"
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data  #contains both ingested train and test dir
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
   schema_file_dir : schema
   schema_file_name: schema.yaml
   data_report_file_name: report.json
   report_page_name: report.html


data_transformation_config:
   transformed_dir: transformed_data  #folder to store transfored train and test data
   transformed_train_dir: train
   transformed_test_dir: test
   preprocessed_dir: preprocessed
   preprocessed_object_file_name: preprocessed.pkl

model_training_config:
   trained_model_dir: trained_model #directory to store model file name
   model_file_name: model.pkl
   base_accuracy: 0.6  #initial base accuracy.

model_evaluation_config:
   model_file_dir : model
   model_name : model.pkl  

model_pusher_config:
   model_export_dir: saved_models #directory to save models